#Start with a base image containing Java runtime
FROM adoptopenjdk/openjdk11

#Create work folder
RUN mkdir /work
RUN chmod 555 /work

# Set environment variable
ENV SECRETSVOL $SECRETSVOL

# Make port 8033 available to the world outside this container
EXPOSE 8033
ARG JAR_FILE=app/target/*.jar
# Copying the application's jar file inside the container
COPY ${JAR_FILE} /work/app.jar

USER nobody
# Run the jar file
CMD java -jar /work/app.jar